//! The handler itself: what tools exist, and the identity the server reports.

use rmcp::handler::server::tool::{ToolCallContext, ToolRouter};
use rmcp::model::{
    CacheScope, CallToolRequestParams, CallToolResponse, GetPromptRequestParams, GetPromptResponse,
    Implementation, ListPromptsResult, ListResourcesResult, ListToolsResult,
    PaginatedRequestParams, ProtocolVersion, ReadResourceRequestParams, ReadResourceResponse,
    ResultType, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::RequestContext;
use rmcp::{ErrorData, RoleServer, ServerHandler};
use sure_core::McpMode;

use crate::config::McpConfig;
use crate::error::to_mcp;
use crate::state::McpState;

/// The MCP server. One is built per request by the transport; every field is cheap to clone.
#[derive(Clone)]
pub struct SureMcp {
    pub(crate) state: McpState,
    pub(crate) config: McpConfig,
}

impl SureMcp {
    pub fn new(state: McpState, config: McpConfig) -> Self {
        Self { state, config }
    }

    /// The tools `mode` serves.
    ///
    /// The write tools are *added* here or not at all — they are not registered and then
    /// checked. A mode test inside each handler would be one forgotten `if` away from a
    /// silent write, and would still cost the caller a tool list twice as long as the one
    /// they can use.
    ///
    /// Exhaustive over the mode on purpose: a new mode has to say what it serves rather than
    /// falling into whichever arm happens to be first.
    pub fn router_for(mode: McpMode) -> ToolRouter<Self> {
        match mode {
            // Not "the read tools with writes withheld" — nothing at all. Reached when the
            // household has switched agent access off in the app while `SURE_MCP` still
            // permits it, so the endpoint is mounted but must serve no surface.
            McpMode::Off => ToolRouter::new(),
            McpMode::Read => {
                Self::reference_router()
                    + Self::transactions_router()
                    + Self::reports_router()
                    + Self::accounts_router()
                    + Self::rules_read_router()
            }
            McpMode::Write => Self::router_for(McpMode::Read) + Self::writes_router(),
        }
    }

    /// What this request may do: the stored setting, clamped to the environment's ceiling.
    ///
    /// Read per request rather than cached. It is one indexed single-row `SELECT` — the same
    /// cost as the currency table every money-rendering tool already reads — and it means a
    /// toggle in the app takes effect on the next call with nothing to invalidate. A cached
    /// copy would also have to be refreshed by the config-import path and by anything that
    /// edits the database directly, and being wrong in the permissive direction is the whole
    /// failure this design is trying to avoid.
    pub async fn effective_mode(&self) -> Result<McpMode, ErrorData> {
        // `Off` cannot be raised by anything, so a deployment that forbids MCP pays nothing
        // to keep saying so.
        if self.config.ceiling == McpMode::Off {
            return Ok(McpMode::Off);
        }
        let stored = self.state.settings.mcp_mode().await.map_err(to_mcp)?;
        Ok(self.config.ceiling.min(stored))
    }

    /// The tools `config` would serve at `mode`, without needing a live [`McpState`].
    pub fn tool_names_for(mode: McpMode) -> Vec<Tool> {
        Self::router_for(mode).list_all()
    }

    /// Each currency's minor-unit scale, keyed by code.
    ///
    /// Every tool that renders money needs it, and the table is a handful of rows that the
    /// pool answers from cache — cheaper to re-read per call than to hold a snapshot that
    /// could go stale the moment someone adds a currency.
    pub(crate) async fn currency_decimals(
        &self,
    ) -> crate::error::ToolResult<std::collections::HashMap<String, u32>> {
        Ok(self
            .state
            .currencies
            .list()
            .await
            .map_err(crate::error::to_mcp)?
            .into_iter()
            // A negative or absurd scale cannot come from the schema, but `decimal_places`
            // is an `i64` and `Decimal::new` takes a `u32`; clamping keeps this total
            // rather than panicking on a hand-edited row.
            .map(|c| (c.code, c.decimal_places.clamp(0, 8) as u32))
            .collect())
    }

    /// The scale for one currency, falling back to the two decimal places almost every
    /// currency has.
    pub(crate) fn scale_of(decimals: &std::collections::HashMap<String, u32>, code: &str) -> u32 {
        decimals.get(code).copied().unwrap_or(2)
    }
}

/// What a client is told about this server on connect.
///
/// Written out rather than generated by `#[tool_handler]`: that macro builds `call_tool` and
/// `list_tools` around one router fixed when the handler was constructed, and the whole point
/// here is that the router follows a setting the household can change while the server runs.
/// The macro skips any method already present, so the difference is only that these three are
/// spelled out.
impl ServerHandler for SureMcp {
    fn get_info(&self) -> ServerInfo {
        let mut info = ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .enable_prompts()
                .build(),
        );
        // `ServerInfo::new` fills this from `CARGO_*` — but those are expanded inside `rmcp`,
        // so the default identifies the SDK ("rmcp 3.1.2") rather than this server. A client
        // listing several connections shows that name.
        info.server_info = Implementation::new("sure", env!("CARGO_PKG_VERSION"))
            .with_title("Sure — personal finance ledger");
        info.instructions = Some(INSTRUCTIONS.to_string());
        info
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, ErrorData> {
        // The gate, and the only one: a tool the current mode does not serve is not in this
        // router, so the router answers "tool not found" exactly as it would for a name that
        // never existed.
        let router = Self::router_for(self.effective_mode().await?);
        router
            .call(ToolCallContext::new(self, request, context))
            .await
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        let tools = Self::router_for(self.effective_mode().await?).list_all();
        let mut result = ListToolsResult::with_all_items(tools);
        // A client may cache a tool list, and this one changes when someone flips a switch in
        // the app — so it is explicitly not cacheable. (The macro's version offers `ttl_ms: 0`
        // for the same reason; said out loud here because the list really is mutable.)
        if context
            .protocol_version()
            .is_some_and(|v| v >= ProtocolVersion::V_2026_07_28)
        {
            result.ttl_ms = Some(0);
            result.cache_scope = Some(CacheScope::Public);
        }
        result.result_type = Some(ResultType::COMPLETE);
        Ok(result)
    }

    /// The transport reads this only to find a tool's *input schema*, and caches it per name
    /// — so it is answered from the ceiling rather than the current mode. A schema is not an
    /// authorisation, and `call_tool` above is what decides whether a tool may run.
    fn get_tool(&self, name: &str) -> Option<Tool> {
        Self::router_for(self.config.ceiling).get(name).cloned()
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        Ok(self.resource_list())
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, ErrorData> {
        self.resource_read(&request.uri).await
    }

    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListPromptsResult, ErrorData> {
        Ok(self.prompt_list())
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<GetPromptResponse, ErrorData> {
        self.prompt_get(&request.name, request.arguments.as_ref())
    }
}

const INSTRUCTIONS: &str = "\
Sure is one household's personal finance ledger: accounts, transactions, categories, \
merchants, rules and reports. The data is real money, not a sample.

Conventions:
- Amounts are already decimal strings paired with a currency code (\"-42.50\", \"NZD\"). \
  Do not divide or multiply them. A negative amount is money out.
- Dates are ISO-8601 (YYYY-MM-DD). Prefer the `range` argument (last_month, last_90_days, \
  ytd, last_12_months, all_time) over computing dates yourself.
- Reports normalise to the household's base currency. Where a currency has no exchange \
  rate its transactions are excluded and named in `unconverted` — say so if it is non-empty, \
  because the total is otherwise incomplete without looking it.

Choosing a tool:
- To total or compare spending, use summarize_spending. Do not fetch rows and add them up.
- To find or inspect specific transactions, use search_transactions.
- list_accounts, list_categories and list_merchants give the ids every other tool takes.

The available tools can change while you are connected: the household can turn agent access \
off, or down to read-only, from the app's settings. If a tool you saw earlier reports that it \
does not exist, list the tools again rather than assuming a bug.";
