#!/usr/bin/env bash
# Remove all build output, dependencies, and dev/test artifacts, returning the
# working tree to a fresh-clone state (tracked files are left untouched). Run via
# `pnpm clean`. Everything removed here is git-ignored and regenerated by
# `pnpm install`, `pnpm build`, or a dev/test run.
set -euo pipefail
cd "$(dirname "$0")/.."

# Print each path only if it exists, then remove it.
rm_path() {
  for p in "$@"; do
    if [ -e "$p" ]; then
      echo "  rm $p"
      rm -rf "$p"
    fi
  done
}

echo "Cleaning node_modules…"
find . -name node_modules -type d -prune -print -exec rm -rf {} +

echo "Cleaning Rust build output…"
rm_path target

echo "Cleaning frontend build + generated client…"
rm_path packages/web/dist packages/web/dist-ssr packages/web/.vite
rm_path packages/client/openapi.json

echo "Cleaning test artifacts…"
rm_path packages/web/test-results packages/web/playwright-report \
        packages/web/blob-report packages/web/.playwright \
        packages/web/tests/.server.pid
rm_path packages/api-tests/test-results packages/api-tests/playwright-report \
        packages/api-tests/blob-report
rm_path .playwright-mcp

echo "Cleaning dev/test databases…"
rm_path data
# Catch any stray SQLite files created outside data/ (node_modules pruned so we
# never touch a dependency's fixtures). find exits 0 even when nothing matches.
find . -name node_modules -prune -o -type f \
  \( -name '*.db' -o -name '*.db-shm' -o -name '*.db-wal' \) -print -delete

echo "Clean complete."
