use utoipa::OpenApi;

/// The OpenAPI document. It's declared independently of the Axum router (rather than
/// via an auto-collecting integration) so it stays decoupled from the web framework's
/// version churn. `paths(...)` and `schemas(...)` are extended as endpoints are added;
/// the `gen-openapi` binary serialises this to JSON for the TypeScript client.
#[derive(Debug, OpenApi)]
#[openapi(
    info(
        title = "Sure API",
        version = "0.1.0",
        description = "Local financial tracker API."
    ),
    paths(
        crate::routes::health::health,
        crate::routes::currencies::list,
        crate::routes::currencies::create,
        crate::routes::currencies::delete,
        crate::routes::settings::get_settings,
        crate::routes::settings::update_settings,
        crate::routes::categories::list,
        crate::routes::categories::tree,
        crate::routes::categories::create,
        crate::routes::categories::update,
        crate::routes::categories::delete,
        crate::routes::merchants::list,
        crate::routes::merchants::create,
        crate::routes::merchants::update,
        crate::routes::merchants::delete,
        crate::routes::accounts::list,
        crate::routes::accounts::get_one,
        crate::routes::accounts::create,
        crate::routes::accounts::update,
        crate::routes::accounts::delete,
        crate::routes::accounts::set_secured_by,
        crate::routes::transactions::list,
        crate::routes::transactions::get_one,
        crate::routes::transactions::create,
        crate::routes::transactions::update,
        crate::routes::transactions::delete,
        crate::routes::transactions::bulk_update,
        crate::routes::transactions::bulk_delete,
        crate::routes::transactions::link,
        crate::routes::transactions::unlink,
        crate::routes::transactions::create_transfer,
        crate::routes::rules::list,
        crate::routes::rules::get_one,
        crate::routes::rules::create,
        crate::routes::rules::update,
        crate::routes::rules::delete,
        crate::routes::rules::run_one,
        crate::routes::rules::run_all,
        crate::routes::rules::preview,
        crate::routes::rules::list_runs,
        crate::routes::rules::run_applications,
        crate::routes::rules::undo_run,
        crate::routes::valuations::list,
        crate::routes::valuations::create,
        crate::routes::valuations::delete,
        crate::routes::reports::net_worth,
        crate::routes::reports::category_breakdown,
        crate::routes::reports::sankey,
        crate::routes::reports::balances,
        crate::routes::reports::equity_position,
        crate::routes::crons::list,
        crate::routes::crons::create,
        crate::routes::crons::update,
        crate::routes::crons::delete,
        crate::routes::crons::run_one,
        crate::routes::crons::run_all,
        crate::routes::crons::list_runs,
        crate::routes::crons::undo_run,
        crate::routes::equity::list_grants,
        crate::routes::equity::create_grant,
        crate::routes::equity::update_grant,
        crate::routes::equity::delete_grant,
        crate::routes::equity::list_exercises,
        crate::routes::equity::create_exercise,
        crate::routes::equity::delete_exercise,
        crate::routes::equity::grant_vesting,
        crate::routes::equity::account_equity,
        crate::routes::equity::revalue,
        crate::routes::brokerage::snapshot,
        crate::routes::brokerage::list_holdings,
        crate::routes::brokerage::create_holding,
        crate::routes::brokerage::delete_holding,
        crate::routes::brokerage::list_dividends,
        crate::routes::brokerage::import,
        crate::routes::brokerage::revalue,
        crate::routes::brokerage::backfill,
        crate::routes::providers::kinds,
        crate::routes::providers::discover_accounts,
        crate::routes::providers::list,
        crate::routes::providers::create,
        crate::routes::providers::link,
        crate::routes::providers::link_group,
        crate::routes::providers::update,
        crate::routes::providers::delete,
        crate::routes::providers::sync,
        crate::routes::providers::list_syncs,
        crate::routes::snapshot::export,
        crate::routes::snapshot::import,
        crate::routes::stock_prices::get_price,
    ),
    components(schemas(
        crate::error::ErrorBody,
        crate::error::ErrorDetail,
        crate::routes::health::Health,
        crate::routes::currencies::Currency,
        crate::routes::currencies::NewCurrency,
        crate::routes::settings::Settings,
        crate::routes::settings::UpdateSettings,
        crate::routes::categories::Category,
        crate::routes::categories::CategoryNode,
        crate::routes::categories::SaveCategory,
        crate::routes::merchants::Merchant,
        crate::routes::merchants::SaveMerchant,
        crate::routes::accounts::Account,
        crate::routes::accounts::AccountKind,
        crate::routes::accounts::AccountClass,
        crate::routes::accounts::AccountMetadata,
        crate::routes::accounts::RateType,
        crate::routes::accounts::DepositoryMeta,
        crate::routes::accounts::PropertyMeta,
        crate::routes::accounts::MortgageMeta,
        crate::routes::accounts::LoanMeta,
        crate::routes::accounts::VehicleMeta,
        crate::routes::accounts::SharesMeta,
        crate::routes::accounts::BrokerageMeta,
        crate::routes::accounts::GenericMeta,
        crate::routes::accounts::SaveAccount,
        crate::routes::accounts::SetSecuredBy,
        crate::routes::transactions::Transaction,
        crate::routes::transactions::SaveTransaction,
        crate::routes::transactions::BulkUpdate,
        crate::routes::transactions::BulkDelete,
        crate::routes::transactions::BulkResult,
        crate::routes::transactions::LinkRequest,
        crate::routes::transactions::TransferRequest,
        crate::routes::rules::Rule,
        crate::routes::rules::SaveRule,
        crate::routes::rules::RuleRun,
        crate::routes::rules::RuleApplicationDetail,
        crate::routes::rules::RunResult,
        crate::routes::rules::PreviewRequest,
        crate::routes::rules::RulePreview,
        crate::routes::rules::PreviewMatch,
        crate::routes::valuations::Valuation,
        crate::routes::valuations::NewValuation,
        crate::routes::reports::NetWorthPoint,
        crate::routes::reports::NetWorthSeries,
        crate::routes::reports::CategoryTotal,
        crate::routes::reports::CategoryBreakdown,
        crate::routes::reports::SankeyNode,
        crate::routes::reports::SankeyLink,
        crate::routes::reports::SankeyGraph,
        crate::routes::reports::AccountBalance,
        crate::routes::reports::BalancesReport,
        crate::routes::reports::SecuredLiability,
        crate::routes::reports::EquityPosition,
        crate::routes::crons::Cron,
        crate::routes::crons::SaveCron,
        crate::routes::crons::CronRun,
        crate::routes::crons::CronRunResult,
        crate::routes::equity::EquityGrant,
        crate::routes::equity::SaveGrant,
        crate::routes::equity::EquityExercise,
        crate::routes::equity::SaveExercise,
        crate::routes::equity::VestingStatus,
        crate::routes::equity::AccountEquity,
        crate::routes::brokerage::HoldingLot,
        crate::routes::brokerage::SaveHoldingLot,
        crate::routes::brokerage::Position,
        crate::routes::brokerage::WalletBalance,
        crate::routes::brokerage::BrokerageSnapshot,
        crate::routes::brokerage::Dividend,
        crate::routes::brokerage::DividendWithholding,
        crate::routes::brokerage::DividendDetail,
        crate::routes::brokerage::BrokerageImportResult,
        crate::routes::brokerage::BackfillResult,
        crate::routes::providers::Provider,
        crate::routes::providers::SaveProvider,
        crate::routes::providers::LinkProviderAccount,
        crate::routes::providers::LinkProviderGroup,
        crate::routes::providers::LinkGroupMember,
        crate::routes::providers::SyncRequest,
        crate::routes::providers::ProviderSync,
        sure_core::ProviderKind,
        sure_core::ProviderAccount,
        crate::routes::stock_prices::StockPrice,
    )),
    tags(
        (name = "meta", description = "Service metadata"),
        (name = "currencies", description = "Currencies"),
        (name = "settings", description = "Global settings"),
        (name = "categories", description = "Categories (nested)"),
        (name = "merchants", description = "Merchants (payees)"),
        (name = "accounts", description = "Financial accounts"),
        (name = "transactions", description = "Transactions & transfers"),
        (name = "rules", description = "Auto-classification rules & audit"),
        (name = "valuations", description = "Account valuations"),
        (name = "reports", description = "Aggregated report data"),
        (name = "crons", description = "Scheduled adjustments"),
        (name = "equity", description = "Equity grants & vesting"),
        (name = "brokerage", description = "Brokerage holdings, wallets & import"),
        (name = "providers", description = "External provider integrations"),
        (name = "config", description = "Config snapshot export/import"),
    )
)]
pub struct ApiDoc;
