//! Browser-facing hardening: the response headers that constrain what a page may do with
//! our output, and the CORS policy that decides who may read it at all.

use axum::http::{header, HeaderName, HeaderValue};
use axum::Router;
use tower_http::cors::{AllowMethods, AllowOrigin, CorsLayer};
use tower_http::set_header::SetResponseHeaderLayer;

use crate::config::ApiConfig;

/// Headers applied to every response, including the ones generated by the limiters.
///
/// * `nosniff` — the API returns JSON and the SPA returns typed assets; letting a browser
///   guess a different type is only ever a way to get something executed.
/// * `Referrer-Policy: no-referrer` — account and transaction ids live in our URLs, and
///   there is no reason to leak them to anything the user navigates to.
/// * `X-Frame-Options: DENY` — nothing should embed a financial app it can then overlay.
/// * `Cross-Origin-Opener-Policy: same-origin` — severs the window handle a popup opener
///   would otherwise keep.
///
/// Names are kept as `&str` rather than `HeaderName`: a `HeaderName` holds interior
/// mutability, which a `const` slice can't. `HeaderName::from_static` is a cheap,
/// non-allocating conversion for lowercase literals like these.
const STATIC_HEADERS: &[(&str, &str)] = &[
    ("x-content-type-options", "nosniff"),
    ("referrer-policy", "no-referrer"),
    ("x-frame-options", "DENY"),
    ("cross-origin-opener-policy", "same-origin"),
];

/// Apply [`STATIC_HEADERS`] to every response the router produces.
///
/// One `SetResponseHeaderLayer` per header rather than a single hand-written middleware:
/// `if_not_present` gives exactly the semantics wanted (a handler with a reason to differ
/// keeps its own value) and the layers compose without an extra future in the path.
pub fn with_security_headers(router: Router) -> Router {
    STATIC_HEADERS.iter().fold(router, |router, (name, value)| {
        router.layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static(name),
            HeaderValue::from_static(value),
        ))
    })
}

/// The CORS policy, or `None` when no cross-origin access is configured.
///
/// There is **no authentication on this API**: a request that reaches it is served. CORS
/// is therefore the only thing standing between an arbitrary page in the user's browser
/// and `GET /api/config/export`, which returns the entire database. It is an allowlist for
/// that reason, and credentials are never enabled (they would let a future cookie ride
/// along on those cross-origin reads).
///
/// The SPA itself never needs this — it is same-origin in development (Vite proxies
/// `/api`) and in production (the binary serves `WEB_DIR`). The allowlist exists for the
/// deployed hostname and for a dev server pointed straight at the backend.
pub fn cors_layer(config: &ApiConfig) -> Option<CorsLayer> {
    let origins: Vec<HeaderValue> = config
        .cors_allowed_origins
        .iter()
        .filter_map(|origin| match HeaderValue::from_str(origin) {
            Ok(value) => Some(value),
            Err(_) => {
                tracing::warn!(%origin, "ignoring unparseable CORS origin");
                None
            }
        })
        .collect();

    if origins.is_empty() {
        tracing::debug!("CORS disabled: no allowed origins configured");
        return None;
    }

    tracing::debug!(count = origins.len(), "CORS enabled for configured origins");
    Some(
        CorsLayer::new()
            .allow_origin(AllowOrigin::list(origins))
            .allow_methods(AllowMethods::any())
            .allow_headers([header::CONTENT_TYPE, header::ACCEPT, header::IF_NONE_MATCH])
            // Let a cross-origin caller read the validator, so conditional requests work
            // from those origins too.
            .expose_headers([header::ETAG, header::CACHE_CONTROL]),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cors_is_disabled_when_no_origins_are_configured() {
        let config = ApiConfig {
            cors_allowed_origins: vec![],
            ..ApiConfig::default()
        };
        assert!(cors_layer(&config).is_none());
    }

    #[test]
    fn unparseable_origins_are_dropped_not_fatal() {
        let config = ApiConfig {
            cors_allowed_origins: vec!["https://ok.example".into(), "bad\nvalue".into()],
            ..ApiConfig::default()
        };
        assert!(cors_layer(&config).is_some());
    }

    #[test]
    fn the_default_allowlist_is_not_a_wildcard() {
        let config = ApiConfig::default();
        assert!(!config.cors_allowed_origins.is_empty());
        assert!(
            !config.cors_allowed_origins.iter().any(|o| o == "*"),
            "an unauthenticated API must never allow every origin"
        );
    }
}
